/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main. java
 *
 * Created on 05-jun-2009, 20:47:43
 */

package botiga;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.security.NoSuchProviderException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import utils.Utils;

public class Main extends javax.swing.JFrame
{
    private Clientes[] arrayClientes;
    private Productos[] arrayProductos;
    private boolean[] editabeClientes = {false,false,false,true};
    private boolean isAdmin = false;
    int userActual = 0, compraTotal = 0;
    int[] prodComprados = null;
    private int[] arrayTotal;

    /** Creates new form Main */
    public Main() throws IOException {
        arrayClientes = new Clientes[50];
        arrayProductos = new Productos[100];
        initComponents();
        this.setSize(260, 150);
        canviarTitol("Login");
        centrarFinestra(this);
        this.setResizable(false);
        jpnAdmin.setVisible(false);
        jpnUser.setVisible(false);
        File fitxer = new File("src\\ficheros\\clientes.dat");
        File fitxer2 = new File("src\\ficheros\\productos.dat");
        
        if(fitxer.isFile() == false) fitxer.createNewFile();
        if(fitxer2.isFile() == false) fitxer2.createNewFile();

        Clientes aux = new Clientes();
        arrayClientes = aux.cargarClientes(fitxer);

        Productos aux2 = new Productos();
        arrayProductos = aux2.cargarProductos(fitxer2);
    }
    private void canviarTitol(String titol)
    {
        this.setTitle(titol);
    }

    private void centrarFinestra(Main aThis)
    {
        //Tomo el tamaño de la pantalla
        Dimension pantallaTamano = Toolkit.getDefaultToolkit().getScreenSize();
        //El ancho de la pantalla lo divido en 2 y le resto la mitad del ancho de mi ventana, con eso queda centrada en el eje X, para el eje Y es lo mismo pero con el alto:
        aThis.setLocation((pantallaTamano.width/2)-(aThis.getWidth()/2), (pantallaTamano.height/2)-(aThis.getHeight()/2));
    }
    private void centrarRegistre(JDialog aThis)
    {
        //Tomo el tamaño de la pantalla
        Dimension pantallaTamano = Toolkit.getDefaultToolkit().getScreenSize();
        //El ancho de la pantalla lo divido en 2 y le resto la mitad del ancho de mi ventana, con eso queda centrada en el eje X, para el eje Y es lo mismo pero con el alto:
        aThis.setLocation((pantallaTamano.width/2)-(aThis.getWidth()/2), (pantallaTamano.height/2)-(aThis.getHeight()/2));
    }


    private void clienteNuevo() {
        jdRegistro.setVisible(true);
        jdRegistro.setSize(650,400);
        centrarRegistre(jdRegistro);
        jdRegistro.setTitle("Registro de nuevo cliente");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdRegistro = new javax.swing.JDialog();
        jtNombre = new javax.swing.JTextField();
        jtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtUser = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        jconfirm_pass = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jcorreo = new javax.swing.JTextField();
        jdAgregarProductos = new javax.swing.JDialog();
        jtnombre = new javax.swing.JTextField();
        jtprecio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtdescripcion = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jpnAdmin = new javax.swing.JPanel();
        jtabPrincipal = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jscrClientes = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jscrProductos = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnInsertar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jpnUser = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        jlbClientes = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jlbNumProd = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jpnLogin = new javax.swing.JPanel();
        jlregistrate = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbnAceptar = new javax.swing.JButton();

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel3.setText("Nombre:");
        jLabel3.setFocusable(false);

        jLabel9.setText("contraseña:");

        jLabel10.setText("User:");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel11.setText(" Por favor introduce el nombre de usuario que deseas y algunos detalles requeridos en la siguiente forma. ");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("confirmar contraseña:");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel12.setText("Apellidos:");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel14.setText("Correo:");

        javax.swing.GroupLayout jdRegistroLayout = new javax.swing.GroupLayout(jdRegistro.getContentPane());
        jdRegistro.getContentPane().setLayout(jdRegistroLayout);
        jdRegistroLayout.setHorizontalGroup(
            jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jdRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jdRegistroLayout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)
                            .addGap(12, 12, 12))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdRegistroLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdRegistroLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdRegistroLayout.createSequentialGroup()
                                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jconfirm_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(115, 115, 115)))
                .addGap(107, 107, 107))
            .addGroup(jdRegistroLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcorreo)
                    .addComponent(jtApellidos)
                    .addComponent(jtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jdRegistroLayout.setVerticalGroup(
            jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jconfirm_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jdRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(27, 27, 27))
        );

        jtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtprecioActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setText("Nombre:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setText("Precio:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel17.setText("Descripcion:");

        jtdescripcion.setColumns(20);
        jtdescripcion.setRows(5);
        jScrollPane5.setViewportView(jtdescripcion);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel18.setText("€");

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdAgregarProductosLayout = new javax.swing.GroupLayout(jdAgregarProductos.getContentPane());
        jdAgregarProductos.getContentPane().setLayout(jdAgregarProductosLayout);
        jdAgregarProductosLayout.setHorizontalGroup(
            jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAgregarProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel15))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdAgregarProductosLayout.createSequentialGroup()
                        .addGroup(jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addGroup(jdAgregarProductosLayout.createSequentialGroup()
                                .addComponent(jtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jdAgregarProductosLayout.createSequentialGroup()
                            .addComponent(btnAgregar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jdAgregarProductosLayout.setVerticalGroup(
            jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAgregarProductosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdAgregarProductosLayout.createSequentialGroup()
                        .addGroup(jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(jdAgregarProductosLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jdAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnAgregar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtabPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Gestión de los Clientes");

        jscrClientes.setBackground(new java.awt.Color(255, 255, 255));
        jscrClientes.setBorder(null);
        jscrClientes.setPreferredSize(new java.awt.Dimension(452, 402));

        tableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableUsers.setGridColor(new java.awt.Color(140, 140, 140));
        jscrClientes.setViewportView(tableUsers);

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnInsertar.setText("Insertar Cliente");
        btnInsertar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar Cliente");
        btnEliminar.setToolTipText("Eliminar Clientes seleccionados");
        btnEliminar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel7.setText("** Al presionar el boton \"Eliminar Cliente\" se borraran todos los clientes seleccionados de la tabla.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel13.setText("* Editar directamente los valores de la tabla");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jscrClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnInsertar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnEliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir)))
                    .addComponent(jLabel13)
                    .addComponent(jLabel7))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jscrClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jtabPrincipal.addTab("Clientes", null, jScrollPane1, "Gestión de los Clientes");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Gestión de los Productos");

        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscrProductos.setViewportView(tableProducts);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel19.setText("* Editar directamente los valores de la tabla");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel20.setText("** Al presionar el boton \"Eliminar Producto\" se borraran todos los clientes seleccionados de la tabla.");

        btnInsertar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnInsertar1.setText("Insertar Producto");
        btnInsertar1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnInsertar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminar.png"))); // NOI18N
        btnEliminar1.setText("Eliminar Producto");
        btnEliminar1.setToolTipText("Eliminar Productos seleccionados");
        btnEliminar1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnInsertar1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnEliminar1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir1))
                        .addComponent(jscrProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jscrProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar1)
                    .addComponent(btnEliminar1)
                    .addComponent(btnSalir1))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        jtabPrincipal.addTab("Productos", null, jScrollPane2, "Gestión de los Productos");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tienda-virtual.gif"))); // NOI18N

        jLabel23.setText("Bienvenidos a nuestra Tienda Virtual. Espero");

        jLabel24.setText("que os haya gustado.");

        jLabel25.setText("Esta mini tienda se trata del proyecto final de");

        jLabel26.setText("una asignatura de la universidad. Como vereis");

        jLabel27.setText("es muy simple puesto que nos dieron una sola");

        jLabel28.setText("semana para planificar y entregar el Proyecto.");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel29.setText("Desarrolladores:");

        jLabel30.setText("Manuel Ruiz");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel31.setText("ruizmanuel@gmail.com");

        jLabel32.setText("Cristian Castillejo");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel33.setText("info@uniondeprogramadores.com");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel34.setForeground(new java.awt.Color(0, 153, 0));
        jLabel34.setText("Acerca de Nosotros");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addContainerGap(496, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addGap(109, 109, 109)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel22)))
                .addContainerGap(368, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        jtabPrincipal.addTab("About", jScrollPane3);

        javax.swing.GroupLayout jpnAdminLayout = new javax.swing.GroupLayout(jpnAdmin);
        jpnAdmin.setLayout(jpnAdminLayout);
        jpnAdminLayout.setHorizontalGroup(
            jpnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpnAdminLayout.setVerticalGroup(
            jpnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpnUser.setBackground(new java.awt.Color(255, 255, 255));

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableClientesMouseReleased(evt);
            }
        });
        tableClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableClientesKeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tableClientes);

        jlbClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        jlbClientes.setText(" text");
        jlbClientes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel21.setText("Total:");

        jlbNumProd.setFont(new java.awt.Font("Tahoma", 0, 10));
        jlbNumProd.setText("jLabel5");

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        jLabel5.setText("€");

        javax.swing.GroupLayout jpnUserLayout = new javax.swing.GroupLayout(jpnUser);
        jpnUser.setLayout(jpnUserLayout);
        jpnUserLayout.setHorizontalGroup(
            jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbClientes)
                    .addGroup(jpnUserLayout.createSequentialGroup()
                        .addGroup(jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnUserLayout.createSequentialGroup()
                                .addComponent(jlbNumProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComprar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jpnUserLayout.setVerticalGroup(
            jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbClientes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNumProd)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addComponent(btnComprar)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jpnLogin.setBackground(new java.awt.Color(255, 255, 255));
        jpnLogin.setEnabled(false);

        jlregistrate.setForeground(new java.awt.Color(0, 0, 153));
        jlregistrate.setText("Registrarse");
        jlregistrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlregistrateMouseClicked(evt);
            }
        });

        jLabel2.setText("Password:");

        jLabel1.setText("User:");

        jbnAceptar.setText("Aceptar");
        jbnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnLoginLayout = new javax.swing.GroupLayout(jpnLogin);
        jpnLogin.setLayout(jpnLoginLayout);
        jpnLoginLayout.setHorizontalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginLayout.createSequentialGroup()
                .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnLoginLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassword)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                    .addGroup(jpnLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlregistrate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbnAceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnLoginLayout.setVerticalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlregistrate)
                    .addComponent(jbnAceptar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(362, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(338, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAceptarActionPerformed
        String user = txtUser.getText();
        char[] pass = txtPassword.getPassword();
        String passw = "";
        for(int x = 0; x < pass.length ; x++)
        {
            passw += pass[x];
        }
        int buscado = Utils.buscarCliente(arrayClientes, user);
        if(buscado != -1)
        {
            Clientes actual = arrayClientes[buscado];
            if(actual.getPassword().equals(passw))
            {
                userActual = buscado;
                this.setSize(553, 472);
                centrarFinestra(this);
                jpnLogin.setVisible(false);
                if(actual.isAdmin())
                {
                    isAdmin = true;
                    this.setTitle("Admin: "+actual.getNombre());
                    jpnAdmin.setVisible(true);
                    mostrarUsuaris();
                    mostrarProductos();
                }
                else
                {
                    this.setTitle("Cliente: "+actual.getNombre());
                    jpnUser.setVisible(true);
                    mostrarClientes();
                }
            }
        }
        else
        {
            String texto[] = {"Usuario o contraseña incorrectos.","Si aún no eres cliente pulsa 'Registrarse'"};
            String cabecera = "Error de login";
            optionPane2(texto, cabecera);
        }
    }//GEN-LAST:event_jbnAceptarActionPerformed

    private void jlregistrateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlregistrateMouseClicked
        clienteNuevo();
    }//GEN-LAST:event_jlregistrateMouseClicked

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       char[] password2 = jpassword.getPassword();
       char[] confirm2 =jconfirm_pass.getPassword();
       String nombre = jtNombre.getText();
       String apellidos =jtApellidos.getText();
       String user= jtUser.getText();
       String correo = jcorreo.getText();
       int encontrado = -1;
       String password = "";
       for(int x = 0; x < password2.length ; x++)
       {
           password += password2[x];
       }
       String confirm = "";
       for(int x = 0; x < confirm2.length ; x++)
       {
           confirm += confirm2[x];
       }

       if(!user.isEmpty())
       {
            encontrado = Utils.buscarCliente(arrayClientes, user);
       }
       // bloque de validaciones
       int formulario_ok = 0;

        if(nombre.isEmpty())
        {
            String texto = "No has introducido tu nombre";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
        else if(apellidos.isEmpty())
        {
            String texto = "No has introducido tus apellidos";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
        else if(correo.isEmpty())
        {
            String texto = "No has introducido el correo";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
        else if((!correo.contains("@"))||(!correo.contains(".")))
        {
            String texto = "Error en el formato del correo ( usuario@dominio.com )";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
        else if(user.isEmpty())
        {
            String texto = "No has introducido el nombre de usuario";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
        else if(encontrado != -1)
        {
            String texto = "El nombre de usuario ya existe";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
       else if(password.isEmpty())
       {
            String texto = "No has introducido el password";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
       else if(password.length()<5)
       {
            String texto = " El password ha de contener más de 4 carácteres";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }

        else if(confirm.isEmpty() || (password.equals(confirm) == false))
        {
            String texto = "La contraseña debe coincidir en los 2 campos";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
        else
        {
           formulario_ok = 1;
        }
    
       if(formulario_ok ==1){
           arrayClientes = Utils.insertarCliente(arrayClientes, nombre, apellidos, password, user, correo);
           if(isAdmin)
           {
               mostrarUsuaris();
           }
           else
           {
               String texto = " Estimado sr/a "+nombre+" ,Le damos la bienvenida a nuestra tienda";
               JOptionPane.showMessageDialog(new JFrame(), texto, "Los datos han sido registrados correctamente ", JOptionPane.INFORMATION_MESSAGE);
           }
           jdRegistro.setVisible(false);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jdRegistro.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(isAdmin)
        {
            Clientes aux = new Clientes();
            arrayClientes = Utils.guardarTablaClientes(arrayClientes,tableUsers);
            aux.guardarClientes(arrayClientes);
            
            
            Productos aux2 = new Productos();
            arrayProductos = Utils.guardarTablaProductos(arrayProductos,tableProducts);
            aux2.guardarProductos(arrayProductos);


        }
        else
        {
            Clientes aux = new Clientes();
            aux.guardarClientes(arrayClientes);
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        jpassword.setText("");
        jconfirm_pass.setText("");
        jtNombre.setText("");
        jtApellidos.setText("");
        jtUser.setText("");
        clienteNuevo();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filas[] = tableUsers.getSelectedRows();
        if(filas.length > 0)
        {
            for(int x = filas.length-1; x >= 0; x--)
            {
                Utils.eliminarCliente(arrayClientes, filas[x]);
            }
            mostrarUsuaris();
        }
        else
        {
            String texto = "No has seleccionado ningún usuario";
            String cabecera = "Error de borrado";
            optionPane(texto,cabecera);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if(isAdmin)
        {
            Clientes aux = new Clientes();
            arrayClientes = Utils.guardarTablaClientes(arrayClientes,tableUsers);
            aux.guardarClientes(arrayClientes);

            Productos aux2 = new Productos();
            arrayProductos = Utils.guardarTablaProductos(arrayProductos,tableProducts);
            aux2.guardarProductos(arrayProductos);
        }
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtprecioActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtprecioActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       String producto = jtnombre.getText();
       String precio =jtprecio.getText();
       String descripcion= jtdescripcion.getText();
       int price = 0;
       if(!precio.isEmpty())
       {
            price = Utils.leerEntero(precio);
       }

       // bloque de validaciones
         int formulario_ok = 0;

         if(producto.isEmpty())
        {
            String texto = "No has introducido el nombre del producto";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
        else if(precio.isEmpty())
        {
            String texto = "No has introducido el precio";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
         else if(price < 0 )
        {
            String texto = "Cuidado has introducido un precio negativo o no has introducido un entero";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
        else if(descripcion.isEmpty())
        {
            String texto = "No has introducido la descripcion del producto";
            String cabecera = "Error en registro ";
            optionPane(texto,cabecera);
        }
          else
        {
           formulario_ok = 1;
        }

       if(formulario_ok ==1){// producto = nombre del producto
           arrayProductos = Utils.insertarProductos(arrayProductos, producto, descripcion,price); // price es el precio pero en un int
           if(isAdmin)
           {
               mostrarProductos();
           }
           else
           {
               String texto = " producto agregado correctamente";
               JOptionPane.showMessageDialog(new JFrame(), texto, "Los datos han sido registrados correctamente ", JOptionPane.INFORMATION_MESSAGE);
           }
           jdAgregarProductos.setVisible(false);
       }
}//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jdAgregarProductos.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnInsertar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertar1ActionPerformed
        jtnombre.setText("");
        jtprecio.setText("");
        jtdescripcion.setText("");
        jdAgregarProductos.setVisible(true);
        jdAgregarProductos.setSize(500,500);
        centrarRegistre(jdAgregarProductos);
        jdAgregarProductos.setTitle("Añadir Productos");
    }//GEN-LAST:event_btnInsertar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        int filas[] = tableProducts.getSelectedRows();
        if(filas.length > 0)
        {
            for(int x = filas.length-1; x >= 0; x--)
            {
                Utils.eliminarProducto(arrayProductos, filas[x]);
            }
            mostrarProductos();
        }
        else
        {
            String texto = "No has seleccionado ningún producto";
            String cabecera = "Error de borrado";
            optionPane(texto,cabecera);
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        if(isAdmin)
        {
            Clientes aux = new Clientes();
            arrayClientes = Utils.guardarTablaClientes(arrayClientes,tableUsers);
            aux.guardarClientes(arrayClientes);

            Productos aux2 = new Productos();
            arrayProductos = Utils.guardarTablaProductos(arrayProductos,tableProducts);
            aux2.guardarProductos(arrayProductos);
        }
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        boolean enviar = false;
        if((arrayProductos[0] != null)&&(prodComprados != null))
        {
            String mensajeEnviar = "<br>Grácias por comprar en nuestra tienda. En menos de 48 horas lo recibirá.<br>";
            mensajeEnviar += "<br/><table width='90%' border='0' cellpadding='0' cellspacing='0' align='left'><tr><td colspan='2' align='left' style='font-size: 15px;'><b>Datos del cliente:</b></br></td></tr><tr><td colspan='2'>&nbsp;</td></tr><tr><td width='10%'><b>Nombre:</b></td><td>"+arrayClientes[userActual].getNombre()+"</td></tr>";
            mensajeEnviar += "<tr><td width='10%'><b>Apellidos:</b></td><td>"+arrayClientes[userActual].getApellidos()+"</td></tr><tr><td width='10%'><b>UserName:</b></td><td>"+arrayClientes[userActual].getUserName()+"</td></tr></table>";
            mensajeEnviar += "<br><br><br><table width='90%' border='1px' cellpadding='0' cellspacing='0' align='left'><tr><td colspan='2' align='left' style='font-size: 15px;'><b>Datos de la compra:</b></br></td></tr><tr><td colspan='2'>&nbsp;</td></tr><tr>";
            mensajeEnviar += "<td width='10%'><b>Nombre:</b></td><td width='10%'><b>Descripción:</b></td><td width='10%'><b>Precio:</b></td><td width='10%'><b>Cantidad:</b></td><td width='10%'><b>Total:</b></td></tr>";
            for(int x = 0; x < prodComprados.length; x++)
            {
                if(prodComprados[x] > 0)
                {
                    enviar = true;
                    mensajeEnviar += "<tr><td align='center'>"+arrayProductos[x].getNombre()+"</td><td align='center'>"+arrayProductos[x].getDescripcion()+"</td><td align='center'>"+arrayProductos[x].getPrecio()+"</td>";
                    mensajeEnviar += "<td align='center'>"+prodComprados[x]+"</td><td align='center'>"+arrayTotal[x]+"</td></tr>";
                }
            }
            mensajeEnviar += "<tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td align='center'>"+compraTotal+" &euro;</td></tr>";
            mensajeEnviar += "</table>";
            String subject = "Procesando pedido";
            if(enviar)
            {
                String[] contenido = new String[]{ arrayClientes[userActual].getNombre()+" hemos registrado su pedido.","En menos de 24 horas recibira un correo con los detalles." };
                JOptionPane.showMessageDialog(new JFrame(), contenido, "Procesando pedido...", JOptionPane.INFORMATION_MESSAGE);
                try {
                    Utils.enviamail(mensajeEnviar,subject,arrayClientes[userActual]);
                } catch (NoSuchProviderException ex)
                {
                } catch (MessagingException ex)
                {
                }
                Clientes aux = new Clientes();
                aux.guardarClientes(arrayClientes);
                System.exit(0);
            }
            else
            {
                String[] contenido2 = new String[]{ "Señor "+arrayClientes[userActual].getNombre()+",","No ha seleccionado ningñn producto para comprar.","¡Gracias!" };
                JOptionPane.showMessageDialog(new JFrame(), contenido2, "¡Escoja sus productos!", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            if(arrayProductos[0] == null)
            {
                String[] contenido = new String[]{ "Lo sentimos señor "+arrayClientes[userActual].getNombre(),"no tenemos ningún producto para venderle."," ","Contacte con el Administrador para mas información","¡Gracias!"," ","Saliendo del Programa..." };
                JOptionPane.showMessageDialog(new JFrame(), contenido, "¡Sin productos!", JOptionPane.WARNING_MESSAGE);
                Clientes aux = new Clientes();
                aux.guardarClientes(arrayClientes);
                System.exit(0);
            }
            else
            {
                String[] contenido = new String[]{ "Señor "+arrayClientes[userActual].getNombre()+",","No ha seleccionado ningñn producto para comprar.","¡Gracias!" };
                JOptionPane.showMessageDialog(new JFrame(), contenido, "¡Escoja sus productos!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    private void tableClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableClientesKeyReleased
        int precio = 0, total = 0, cantidad = 0;
        prodComprados = new int[tableClientes.getRowCount()];
        arrayTotal = new int[tableClientes.getRowCount()];
        String texto = "La cantidad debe ser un entero positivo.";
        String cabecera = "Error en la cantidad";
        for(int x = 0; x < tableClientes.getRowCount(); x++)
        {
            precio = Utils.leerEntero(tableClientes.getValueAt(x, 1).toString());
            cantidad = Utils.leerEntero(tableClientes.getValueAt(x, 3).toString());
            if(cantidad < 0)
            {
                optionPane(texto, cabecera);
                break;
            }
            else
            {
                prodComprados[x] = cantidad;
                total += precio*cantidad;
                arrayTotal[x] = precio*cantidad;
            }
        }
        compraTotal = total;
        txtTotal.setText(""+total);
    }//GEN-LAST:event_tableClientesKeyReleased

    private void tableClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientesMouseReleased
        int precio = 0, total = 0, cantidad = 0;
        prodComprados = new int[tableClientes.getRowCount()];
        arrayTotal = new int[tableClientes.getRowCount()];
        String texto = "La cantidad debe ser un entero positivo.";
        String cabecera = "Error en la cantidad";
        for(int x = 0; x < tableClientes.getRowCount(); x++)
        {
            precio = Utils.leerEntero(tableClientes.getValueAt(x, 1).toString());
            cantidad = Utils.leerEntero(tableClientes.getValueAt(x, 3).toString());
            if(cantidad < 0)
            {
                optionPane(texto, cabecera);
                break;
            }
            else
            {
                prodComprados[x] = cantidad;
                total += precio*cantidad;
                arrayTotal[x] = precio*cantidad;
            }
        }
        compraTotal = total;
        txtTotal.setText(""+total);
    }//GEN-LAST:event_tableClientesMouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnInsertar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbnAceptar;
    private javax.swing.JPasswordField jconfirm_pass;
    private javax.swing.JTextField jcorreo;
    private javax.swing.JDialog jdAgregarProductos;
    private javax.swing.JDialog jdRegistro;
    private javax.swing.JLabel jlbClientes;
    private javax.swing.JLabel jlbNumProd;
    private javax.swing.JLabel jlregistrate;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JPanel jpnAdmin;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JPanel jpnUser;
    private javax.swing.JScrollPane jscrClientes;
    private javax.swing.JScrollPane jscrProductos;
    private javax.swing.JTextField jtApellidos;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtUser;
    private javax.swing.JTabbedPane jtabPrincipal;
    private javax.swing.JTextArea jtdescripcion;
    private javax.swing.JTextField jtnombre;
    private javax.swing.JTextField jtprecio;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTable tableProducts;
    private javax.swing.JTable tableUsers;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void mostrarUsuaris()
    {
        int cont = 0;
        DefaultTableModel modelInicial = new DefaultTableModel(new String[] {"Nombre", "Apellidos","Correo","UserName","Password","Admin"},0);
        tableUsers.setModel(modelInicial);
        DefaultTableModel model = (DefaultTableModel) tableUsers.getModel();

        while(arrayClientes[cont] != null)
        {
            model.addRow(new Object[] {arrayClientes[cont].getNombre(), arrayClientes[cont].getApellidos(), arrayClientes[cont].getCorreo(), arrayClientes[cont].getUserName(), arrayClientes[cont].getPassword(), ""+arrayClientes[cont].getAdmin()});
            cont++;
        }
    }
    private void mostrarProductos()
    {
        int cont = 0;
        DefaultTableModel modelInicial = new DefaultTableModel(new String[] {"Nombre", "Precio € ","Descripcion"}, 0);
        tableProducts.setModel(modelInicial);
        DefaultTableModel model = (DefaultTableModel) tableProducts.getModel();

        while(arrayProductos[cont] != null)
        {
            model.addRow(new Object[] {arrayProductos[cont].getNombre(), arrayProductos[cont].getPrecio(), arrayProductos[cont].getDescripcion()});
            cont++;
        }
    }
    private void mostrarClientes()
    {
        int cont = 0;
        
        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String[] {"Nombre", "Precio € ","Descripcion","Cantidad"}
        ) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return editabeClientes[columnIndex];
            }
        });
        DefaultTableModel model = (DefaultTableModel) tableClientes.getModel();

        while(arrayProductos[cont] != null)
        {
            model.addRow(new Object[] {arrayProductos[cont].getNombre(), arrayProductos[cont].getPrecio(), arrayProductos[cont].getDescripcion(),"0"});
            cont++;
        }
        jlbClientes.setText("Bienvenido "+arrayClientes[userActual].getUserName()+" a nuestra tienda.");
        jlbNumProd.setText("En este momento tenemos "+cont+" producto/s a vuestra disposición.");
    }

    private void optionPane(String texto, String cabecera) {
        JOptionPane.showMessageDialog(new JFrame(), texto, cabecera, JOptionPane.WARNING_MESSAGE);
    }

    private void optionPane2(String[] texto, String cabecera) {
        JOptionPane.showMessageDialog(new JFrame(), texto, cabecera, JOptionPane.WARNING_MESSAGE);
    }

}
